[INFO 2023-05-10 19:30:44,878]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--19-30-44/log.txt
[INFO 2023-05-10 19:30:44,878]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--19-30-44
[INFO 2023-05-10 19:30:44,878]-> Random seed is 1683714644
[INFO 2023-05-10 19:30:44,879]-> A new study created in memory with name: no-name-5192342a-2d2b-4c50-af23-0fcdd0113b6b
[WARNING 2023-05-10 19:30:52,384]-> Trial 0 failed with parameters: {'k': 11, 'hidden_dim': 42, 'lr': 0.004486389035686966, 'weight_decay': 0.004298174941852306} because of the following error: AssertionError('y_true must be 1D torch.LongTensor.').
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 103, in experiment
    val_res = self.validate(self.data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 108, in validate
    return super().validate(data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 131, in validate
    res = self.evaluator.validate(labels[val_mask], outputs[val_mask])
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/hypergraphs/hypergraph.py", line 41, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 150, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/base.py", line 174, in validate
    return self.func_list[self.validate_index](y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 67, in accuracy
    y_true, y_pred = _format_inputs(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 32, in _format_inputs
    assert y_true.dim() == 1, "y_true must be 1D torch.LongTensor."
AssertionError: y_true must be 1D torch.LongTensor.
[WARNING 2023-05-10 19:30:52,385]-> Trial 0 failed with value None.
