[INFO 2023-05-10 19:31:38,430]-> Logs will be saved to /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--19-31-38/log.txt
[INFO 2023-05-10 19:31:38,430]-> Files in training will be saved in /home/adriendutfoy/Desktop/Dev/MultiGraph/examples/logs/2023-05-10--19-31-38
[INFO 2023-05-10 19:31:38,431]-> Random seed is 1683714698
[INFO 2023-05-10 19:31:38,431]-> A new study created in memory with name: no-name-1ebda032-9b43-479f-b1e5-6ee8407eec9e
[WARNING 2023-05-10 19:31:46,766]-> Trial 0 failed with parameters: {'k': 91, 'hidden_dim': 46, 'lr': 0.005972041708168617, 'weight_decay': 0.00021013020032333848} because of the following error: AssertionError('y_true must be 1D torch.LongTensor.').
Traceback (most recent call last):
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 71, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 83, in experiment
    return super().experiment(trial)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/base.py", line 103, in experiment
    val_res = self.validate(self.data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/hypergraphs/hypergraph.py", line 108, in validate
    return super().validate(data, model)
  File "/home/adriendutfoy/.local/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/experiments/vertex_classification.py", line 131, in validate
    res = self.evaluator.validate(labels[val_mask], outputs[val_mask])
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/hypergraphs/hypergraph.py", line 41, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 150, in validate
    return super().validate(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/base.py", line 174, in validate
    return self.func_list[self.validate_index](y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 67, in accuracy
    y_true, y_pred = _format_inputs(y_true, y_pred)
  File "/home/adriendutfoy/Desktop/Dev/MultiGraph/examples/dhg/metrics/classification.py", line 32, in _format_inputs
    assert y_true.dim() == 1, "y_true must be 1D torch.LongTensor."
AssertionError: y_true must be 1D torch.LongTensor.
[WARNING 2023-05-10 19:31:46,767]-> Trial 0 failed with value None.
